folio-org/mod-data-import

src/main/java/org/folio/service/storage/LocalFileStorageService.java, src/test/java/org/folio/rest/AbstractRestTest.java, src/test/java/org/folio/rest/UploadDefinitionAPITest.java
An error occurs when uploading files with certain symbols in the name. Problematic symbols:  { } [ ] ( ) $ (and probably some other symbols).
=> MODDATAIMP-92 : Error when uploading file with certain symbols in name

src/main/java/org/folio/rest/impl/DataImportImpl.java, src/main/java/org/folio/service/fileextension/FileExtensionServiceImpl.java, src/test/java/org/folio/rest/FileExtensionAPITest.java
Currently, there are two validations on the backend exist for creating file extensions:
1. Duplicate file extensions
2. Invalid file extension
Now they are executed in the order specified above which may lead to the wrong results.
*Steps to reproduce:*
1. *.csv* file extension already exists on the server. Make POST request to _data-import/fileExtensions_ endpoint with the following body
```
{
"dataTypes": [],
"description": "",
"extension": "  .csv  ",
"importBlocked": true
}
```
The problem is the *extension* field which has surrounding spaces.
*Expected result:*
The invalid file extension error returns from the server.
```
{
"errors": [
{
"message": "fileExtension.extension.invalid",
"parameters": []
}
],
"total_records": 1
}
```
*Actual result:*
The duplication error returns from the …
=> MODDATAIMP-93 Change validation order for file extension

src/main/java/org/folio/dao/FileExtensionDao.java, src/main/java/org/folio/dao/FileExtensionDaoImpl.java, src/main/java/org/folio/rest/impl/DataImportImpl.java, src/main/java/org/folio/service/fileextension/FileExtensionService.java, src/main/java/org/folio/service/fileextension/FileExtensionServiceImpl.java, src/main/java/org/folio/service/upload/UploadDefinitionService.java, src/main/java/org/folio/service/upload/UploadDefinitionServiceImpl.java, src/test/java/org/folio/rest/DefaultFileExtensionAPITest.java, src/test/java/org/folio/rest/UploadDefinitionAPITest.java
File extensions should be checked during UploadDefinition creation.
If there is a FileExtension with an "importBlocked" == true an error should be returned to the consumer with a message that processing for such a file extension is prohibited.
=> MODDATAIMP-83 Extend file UploadDefinition checking to verify file extensions.

pom.xml, src/test/java/org/folio/rest/AbstractRestTest.java, src/test/java/org/folio/rest/UploadDefinitionAPITest.java
* enabled auto-generation hashCode() and equals();
* updated dependency for record-manager-client;
* fixed tests;
=> MODDATAIMP-138 - Fix data-import tests

Dockerfile, descriptors/ModuleDescriptor-template.json
Use new Alpine base docker image with more recent Java 8 (222) with +UseContainerSupport, and JAVA_OPTIONS MaxRAMPercentage to manage container memory.
See notes at [FOLIO-2358](https://issues.folio.org/browse/FOLIO-2358).
=> MODDATAIMP-222 FOLIO-2358 manage container memory

pom.xml, src/main/java/org/folio/service/processing/reader/MarcXmlReader.java
Dom4j's SAXReader enables external DTDs and External Entities
by default when reading XML files.
This makes mod-data-import vulnerable to XXE attacks:
https://en.wikipedia.org/wiki/XML_external_entity_attack
Fix this by upgrading to latest Dom4j and disabling external DTDs and
External Entities by changing the SAXReader configuration as suggested on
https://github.com/dom4j/dom4j/releases/tag/version-2.1.3
https://cheatsheetseries.owasp.org/cheatsheets/XML_External_Entity_Prevention_Cheat_Sheet.html#saxreader
Reference: https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-10683
=> MODDATAIMP-319: Dom4j XXE vulnerability (CVE-2020-10683)

.rancher-pipeline.yml, NEWS.md, descriptors/ModuleDescriptor-template.json, src/main/resources/log4j2.properties, src/main/resources/vertx-default-jul-logging.properties
1. New config file "vertx-default-jul-logging" for overriding vertx-jul added with disabling(except ERROR log-level) CQL2PgJSON.
2. Disabling CQLWrapper to log4j2.properties added.
3. "-Djava.util.logging.config.file=vertx-default-jul-logging.properties" added for ModuleDescriptor.
4. "-Djava.util.logging.config.file=vertx-default-jul-logging.properties" to the .rancher-config-file.
5. NEWS updated.
=> MODDATIMP-316: Disable CQL2PgJSON & CQLWrapper extra logging in mod-data-import.

descriptors/ModuleDescriptor-template.json
source-manager-records interface dependency is no longer required by mod-data-import
=> Remove unnecessary interface dependency

NEWS.md, PERSONAL_DATA_DISCLOSURE.md
Add personal data disclosure form.
Places a copy of the personal data disclosure form at the top level of the module github repository and checked the boxes that apply.
More info: https://issues.folio.org/browse/MODDATAIMP-348
=> MODDATAIMP-348: Add personal data disclosure form.

src/main/java/org/folio/service/processing/kafka/SourceReaderReadStreamWrapper.java
Ensure exactly once delivery for chunks of records
Generate id for the chunk and skip in SRM if that id violates unique constraint
=> Generate id for RawRecordsDto

NEWS.md, src/main/java/org/folio/service/processing/ParallelFileChunkingProcessor.java
Data import job is not completed with an error when a file parsing error occurs. Data-import should finishes with status "FAILED".
Exception catching added. Moreover, there were changed default current progress number to 0 (was 1). It needs for the status 'FAILED' (Completed with errors without this change)
More info: https://issues.folio.org/browse/MODDATAIMP-388
This PR should be merged with: https://github.com/folio-org/mod-source-record-manager/pull/401
=> MODDATAIMP-388: Import job is not completed on file parsing error [BUGFIX]

NEWS.md, src/main/java/org/folio/service/processing/ParallelFileChunkingProcessor.java, src/test/java/org/folio/service/processing/ParallelFileChunkingProcessorUnitTest.java, src/test/resources/invalidMarcFile.mrc
Job with empty or invalid marc file stucks with invalid (NaN%) progress number. It can be removed.
The main goal - to fix it.
If there are no records or invalid MARC-content (just simple text, for example), then data-import will be finished with Failed status. The job won`t be stuck.
Moreover, added try/catch to the highest level for logging different errors.
More info: https://issues.folio.org/browse/MODDATAIMP-400
=> MODDATAIMP-400: Resolve data-import catching error issues [BUGFIX]

NEWS.md, src/main/java/org/folio/dao/FileExtensionDao.java, src/main/java/org/folio/dao/FileExtensionDaoImpl.java, src/main/java/org/folio/service/fileextension/FileExtensionServiceImpl.java, src/test/java/org/folio/rest/UploadDefinitionAPITest.java
When a file is uploaded for data import, the file extension check should be case-insensitive
* cqlWrapper is used to build case insensitive query for file extension
[MODDATAIMP-413](https://issues.folio.org/browse/MODDATAIMP-413)
=> MODDATAIMP-413 - When a file is uploaded for data import, the file extension check should be case-INsensitive

.rancher-pipeline.yml, pom.xml, src/main/java/org/folio/service/processing/reader/SourceReaderBuilder.java, src/main/resources/templates/db_scripts/schema.json, src/main/resources/templates/db_scripts/update_data_type_for_file_extensions.sql, src/test/java/org/folio/rest/AbstractRestTest.java, src/test/java/org/folio/rest/FileExtensionAPITest.java, src/test/java/org/folio/rest/UploadDefinitionAPITest.java, src/test/java/org/folio/service/processing/ParallelFileChunkingProcessorUnitTest.java
Change record type MARC_BIB for more common type MARC, remove MARC_AUTHORITY and MARC_HOLDING from dataTypes
- changed data type from MARC to MARC_BIB
- created migration script for removing MARC_AUTHORITY, MARC_HOLDING and changing MARC_BIB to MARC
[MODDATAIMP-464](https://issues.folio.org/browse/MODDATAIMP-464)
=> MODDATAIMP-464 Change dataType to have have common type for MARC related subtypes

descriptors/ModuleDescriptor-template.json
since mapping metadata (mapping rules and parameters) should be deleted from the data-import payload it is  necessary to provide permission for modules participating in data-import to retrieve mapping metadata
[MODSOURCE-286](https://issues.folio.org/browse/MODSOURCE-286)
=> MODSOURCE-286 - Add permission for retrieving mapping rules and params

NEWS.md, src/main/java/org/folio/service/storage/LocalFileStorageService.java
Harmless errors for data import show up in the logs as clutter, which makes debugging more difficult.
[https://issues.folio.org/browse/MODDATAIMP-480](url)
=> MODDATAIMP-480 Suppress harmless errors from Data Import logs

src/main/java/org/folio/service/storage/LocalFileStorageService.java
Harmless errors for data import show up in the logs as clutter, which makes debugging more difficult
Reduced logger scope
[https://issues.folio.org/browse/MODDATAIMP-480](url)
=> MODDATAIMP-480 Reduced logging scope for LocalFileStorageService

NEWS.md, src/main/java/org/folio/service/processing/kafka/SourceReaderReadStreamWrapper.java, src/main/java/org/folio/service/processing/reader/SourceReaderBuilder.java, src/test/java/org/folio/service/processing/ParallelFileChunkingProcessorUnitTest.java
since records chunk size depends on record type/format (e.g. xml format has more redundant syntax) it makes sense to have the ability to set records chunk size for particular record type separately
* delete zipping operation for data-import payload before send to Kafka
* provide system properties for SourceReaderBuilder to set records chunk size for each record type and marc format (raw, json, xml) correspondingly
* "file.processing.marc.raw.buffer.chunk.size" property with 50 size value by default for marc raw format
*  "file.processing.marc.json.buffer.chunk.size" property with 50 size value by default for marc json format
*  "file.processing.marc.xml.buffer.chunk.size" property with 10 size value by default for marc xml format (since the xml format is more redundant the proposed …
=> MODDATAIMP-548 - Provide system properties to set chunk size for each marc record format

src/main/java/org/folio/service/processing/ParallelFileChunkingProcessor.java
In Vertx documentation for shared producer usage written: 
`When you are done with the producer, just close it, when all shared producers are closed, the resources will be released for you.`
Link: https://vertx.io/docs/vertx-kafka-client/java/#_sharing_a_producer
In debug mode we see that for we have static map of shared producers(marked as green) that always contains the single item for module mod-data-import, but for every import Vertx creates separate KafkaWriteStream(marked as blue) that contains link to shared producer and designed to write stream of data to Kafka {@link ProducerRecord}.
If we don't invoke producer's close() method, these KafkaWriteStream objects will never be deleted and with every import the map which contains these streams  would grow.
To answer question when …
=> MODDATAIMP-557. Close Vertx Kafka producers that have not been closed

descriptors/ModuleDescriptor-template.json
In mod-inventory app we saw error stack trace and due to that import completes with errors:
`Caused by: org.folio.invoices.rest.exceptions.HttpException: User does not have permissions to manage acquisition units assignments - operation is restricted
at org.folio.utils.UserPermissionsUtil.verifyUserHasAssignPermission(UserPermissionsUtil.java:31) ~[mod-invoice-fat.jar:?]
at org.folio.rest.impl.InvoiceHelper.lambda$6(InvoiceHelper.java:172) ~[mod-invoice-fat.jar:?]`
Mod-Inventory throws this exception if Acq units are presented but permission `invoices.acquisitions-units-assignments.assign` is not provided.
https://github.com/folio-org/mod-invoice/blob/master/src/main/java/org/folio/utils/UserPermissionsUtil.java#L31
Add necessary permission to mod-data-import to be able to successfully …
=> MODDATAIMP-561. Acq unit in invoice field mapping profile causes import to complete with errors

NEWS.md, src/main/java/org/folio/service/processing/kafka/SourceReaderReadStreamWrapper.java, src/main/java/org/folio/service/processing/kafka/WriteStreamWrapper.java
We can change meaningless kafka header "correllationId" to "recordId" and "chunkId".
This changes have to be added to the: data-import, data-import-processing-core, srm, srs, inventory  and other core modules.
Changed "correllationId" to "chunkId". 
Logs improved.
JIRA: https://issues.folio.org/browse/MODDATAIMP-491
=> Moddataimp-491: Improve logging to be able to trace the path of each record and file_chunks

NEWS.md, pom.xml
to fix  vulnerability that is present in log4j<= 2.14
* upgrade log4j to 2.16.0
[MODDATAIMP-598](https://issues.folio.org/browse/MODDATAIMP-598)
=> MODDATAIMP-598 - Critical vulnerability in the Apache log4j

NEWS.md, pom.xml
to fix the vulnerability that is present in log4j<= 2.14
* upgrade log4j version to 2.16.0
[MODDATAIMP-599](https://issues.folio.org/browse/MODDATAIMP-599)
=> MODDATAIMP-599 - Juniper R2 2021 - Log4j vulnerability verification and correction

pom.xml
Using the latest versions helps us avoid possible problems with the libraries.
- upgraded gson from 2.8.6 to 2.8.9
- upgraded data-import-processing-core from 3.2.0 to 3.3.0
[MODDATAIMP-635](https://issues.folio.org/browse/MODDATAIMP-635)
=> MODDATAIMP-635 Check if any 3d party dependencies should be update for DI modules

src/main/java/org/folio/config/ApplicationConfig.java
Even though Kafka message payload was significantly decreased, it is still recommended to adjust MAX_REQUEST_SIZE value to allow importing large files. Setting default value to 4000000 bytes would make adjustment of that property unnecessary.
=> Adjust default MAX_REQUEST_SIZE

NEWS.md, src/main/resources/log4j2.properties
Improve logging. Added FOLIO-approach for retrieving properties for logging.
Retreiving properties from FolioLoggingContext.
- It seems like these properties are available only for REST-requests.
https://issues.folio.org/browse/MODDATAIMP-646
=> MODDATAIMP-646: Logs show incorrectly formatted request id.

NEWS.md, pom.xml, src/main/java/org/folio/dao/UploadDefinitionDaoImpl.java, src/main/java/org/folio/service/fileextension/FileExtensionServiceImpl.java, src/test/java/org/folio/rest/FileExtensionAPITest.java, src/test/java/org/folio/service/cleanup/StorageCleanupServiceImplTest.java
* updated RMB to 34.1.0
* since the PostgresClient.get method which consumes String filter parameter has been deleted from RMB v34.1.0, replaced it with PostgresClient.get method which expects Criterion parameter
* Fixed file extension existence check due to introduced changes in RMB-917
[MODDATAIMP-696](https://issues.folio.org/browse/MODDATAIMP-696)
=> MODDATAIMP-696 - Upgrade RMB to v34.1.0

src/main/java/org/folio/service/processing/kafka/SourceReaderReadStreamWrapper.java
to be able to correlate log messages for the same chunk of records. Spotted during investigation [FAT-3397](https://issues.folio.org/browse/FAT-3397)
Example of log messages that refer to the same chunk of records:
> "Starting to process raw records chunk with id: **1a3ff3c9-2510-4658-b615-dec4cc9586e0** for jobExecutionId: bc6362e6-aa48-40b2-a503-1400d194ad8b. Chunk size: 1."
...
> "Event with type: DI_RAW_RECORDS_CHUNK_PARSED and chunkId: **28aba248-82f6-4656-b869-522f4afa1ef2** was sent to kafka"
> 
> 
* put the actual id of records chunk to Kafka headers
=> FAT-3397 - Put actual chunk id to kafka headers to correlate log messages for particular chunk

descriptors/ModuleDescriptor-template.json
https://issues.folio.org/browse/MODDATAIMP-757
After updating implementation of creating invoice flow the permissinon set has been updated. In order to support these changes in invoice data import flow the permission set in mod-data-import should be updated as well.
Following permissions should be added:
"orders-storage.order-invoice-relationships.item.post",
"finance-storage.budget-expense-classes.collection.get",
"finance.ledgers.collection.get",
"finance.funds.budget.item.get",
"finance-storage.fiscal-years.item.get",
"finance.fiscal-years.item.get",
"finance-storage.budgets.collection.get",
"finance.transactions.collection.get",
"finance.expense-classes.collection.get",
"finance.exchange-rate.item.get"
=> [MODDATAIMP-757]Add missed permissions for invoice data import flow

src/main/resources/log4j2-json.properties, src/main/resources/log4j2.properties
https://issues.folio.org/browse/MODDATAIMP-758HAide SQL requests (org.folio.rest.persist.PostgresClient) from log files for the next modules:
mod-data-import
mod-source-record-storage
mod-data-import-converter-storage
mod-inventory-storage
This class logs SQL queries at the INFO level, which leads to a very large size of log files.
SRS: a lot of messages like this:
2023-01-05 09:28:12.246 WARN AbstractConfig The configuration 'ssl.protocol' was supplied but isn't a known config.
....
2023-01-05 09:28:12.246 WARN AbstractConfig The configuration 'ssl.truststore.type' was supplied but isn't a known config.
SRM: move to TRACE level or decrease defaultRules json
2023-01-05 01:55:50.850 [vert.x-eventloop-thread-1] [572525/proxy;692150/tenant] [diku] [] [mod_source_record_manager] DEBUG …
=> [MODDATAIMP-758]Imrove logging (hide SQL requests)

pom.xml
When trying to execute `mvn install` I encountered the following errors
```
ERROR PostgresClient       Could not find a valid Docker environment. Please see logs and check configuration
java.lang.IllegalStateException: Could not find a valid Docker environment. Please see logs and check configuration
.....
[ERROR] Failures: 
[ERROR]   DefaultFileExtensionAPITest>AbstractRestTest.lambda$setUpClass$1:197 Not equals : Failed to make post tenant. Received status code 400 != Cannot invoke "org.folio.rest.persist.PostgresClient.select(String)" because the return value of "org.folio.rest.impl.TenantAPI.postgresClient(io.vertx.core.Context)" is null
```
My development machine is a Mac with M1 chip
I am locally running Docker Desktop with a configured postgres:12-alpine container
After research, …
=> Update version of test containers to support Mac M1 processor

README.md, descriptors/ModuleDescriptor-template.json, pom.xml, ramls/dataImport.raml, ramls/fileUploadInfo.json, src/main/java/org/folio/config/ApplicationConfig.java, src/main/java/org/folio/rest/impl/DataImportImpl.java, src/main/java/org/folio/service/s3storage/FolioS3ClientFactory.java, src/main/java/org/folio/service/s3storage/MinioStorageService.java, src/main/java/org/folio/service/s3storage/MinioStorageServiceImpl.java, src/main/resources/minio.properties, src/test/java/org/folio/rest/UploadUrlAPITest.java, src/test/java/org/folio/service/s3storage/FolioS3ClientFactoryTest.java, src/test/java/org/folio/service/s3storage/MinioStorageServiceTest.java, src/test/resources/minio.properties
As part of the data import improvement project, we want to upload directly to S3-like storage from the frontend.  This requires obtaining a presigned URL and exposing an endpoint to obtain this URL, which was added as `GET /uploadUrl` (see https://github.com/folio-org/folio-s3-client/pull/11 for the accompanying changes in `folio-s3-client`).
This adds a new endpoint `GET /uploadUrl` and entity `FileUploadInfo` to contain data that allows the frontend client to upload directly to S3.  To accomplish this, infrastructure was added to interface with the FOLIO S3 client.
=> MODDATAIMP-846: Add GET /uploadUrl endpoint

descriptors/ModuleDescriptor-template.json, pom.xml, ramls/dataImport.raml, ramls/fileUploadInfo.json, src/main/java/org/folio/rest/impl/DataImportImpl.java, src/main/java/org/folio/service/s3storage/MinioStorageService.java, src/main/java/org/folio/service/s3storage/MinioStorageServiceImpl.java, src/test/java/org/folio/rest/AbstractRestTest.java, src/test/java/org/folio/rest/UploadUrlAPITest.java, src/test/java/org/folio/service/s3storage/MinioStorageServiceTest.java, src/test/resources/minio.properties
Update the existing `/uploadUrl` endpoint to create a multipart upload; add a new endpoint to get presigned URLs for future parts.
This updates the `MinioStorageService` methods to use multipart.  For testing, `testcontainers` with `LocalStack` was added, which emulates minio/S3.  I found another option for `minio` that was used by `mod-data-export-worker`, however, it relied on Spring/Spring Boot, so I decided `testcontainers` was the best solution.
=> MODDATAIMP-857: Add multipart compatibility to /uploadUrl endpoint

.rancher-pipeline.yml, Dockerfile, Jenkinsfile, NEWS.md, pom.xml
_Upgrade mod-data-import to Java 17._
_Incorporates updating **folio-kafka-wrapper** and **data-import-processing-core** version also migrated to Java 17._
=> MODDATAIMP-854: Upgrade mod-data-import to Java 17

ramls/dataImport.raml, src/main/java/org/folio/rest/impl/DataImportImpl.java, src/main/java/org/folio/service/s3storage/MinioStorageService.java, src/main/java/org/folio/service/s3storage/MinioStorageServiceImpl.java, src/test/java/org/folio/rest/DataImportAssembleFileTest.java, src/test/java/org/folio/service/s3storage/MinioStorageServiceTest.java
Create an API that allows UI to complete an S3 upload.  This api takes in a list of tags created during upload, the file id created by a previous api and the file name called a key.
It uses the Folio S3 client functionality built earlier to complete an upload.
None other then further unit test possibly needed.
eTags are retrieved by the UI as a consequence of uploading file parts to the presigned urls provided.  upload ID is not related to folio ids
=> Moddataimp 874 implement api to combine s3 multi part uploads

src/main/java/org/folio/service/processing/ranking/ScoreUtils.java, src/test/java/org/folio/service/processing/ranking/ScoreUtilsUnboundedExclusionTest.java
Allow reference values of `0` to be used to exclude a metric entirely. 
Add checks before calculating scores to return `0` in these cases, rather than attempting a potentially invalid calclation (divide by zero).
=> [MODDATAIMP-892] Allow zero reference values for excluded metrics

src/main/java/org/folio/dao/DataImportQueueItemDao.java, src/main/java/org/folio/dao/DataImportQueueItemDaoImpl.java, src/main/resources/liquibase/module/scripts/v-0.0.1/2023-08-14--00-00-remove-queue-item-size-column.xml, src/test/java/org/folio/dao/DataImportQueueDaoTest.java
We opted not to consider chunk size as a metric for prioritizing queue items; therefore, this column is no longer needed.
This removes the support from the DAO and provides a Liquibase changelog to drop the column in the database.
=> [MODDATAIMP-894] Remove unused DI queue column `size`

src/main/java/org/folio/rest/impl/DataImportImpl.java, src/test/java/org/folio/rest/FileExtensionAPITest.java
Resolves: [MODDATAIMP-873](https://issues.folio.org/browse/MODDATAIMP-873) Change file extension validation messages which are represented in code format
=> [MODDATAIMP-873] Change file extension validation messages which are represented in code format

descriptors/ModuleDescriptor-template.json
Error is 'org.folio.inventory.consortium.exceptions.ConsortiumException: Error retrieving centralTenantId by tenant id: diku, status code: 403, response message: Access for user 'cypressTestUser673.2125076239648903' (56b0edf3-9064-4bd5-9466-272de43a97de) requires permission: user-tenants.collection.get'.{}
Added permissions for user-tenants collection
=> [MODINV-873] Add permissions for user-tenants collection

src/main/java/org/folio/service/file/SplitFileProcessingService.java, src/test/java/org/folio/service/file/SplitFileProcessingServiceRegistrationTest.java, src/test/java/org/folio/service/file/SplitFileProcessingServiceStartJobTest.java
Remove the race condition that was possible when a job was created/begun processing.  This was possible since, when jobs were created, they were inserted into the queue before fully initialized; as the background workers process from the queue asynchronously, it was possible for there to be enough of a gap here that a job could be grabbed and processed before being properly initialized.
Moved the queue-inserting code to be the last step of job processing/registration.
=> [MODDATAIMP-913] Resolve race condition in job processing/creation

src/main/java/org/folio/rest/impl/DataImportImpl.java, src/main/java/org/folio/service/s3storage/MinioStorageService.java, src/main/java/org/folio/service/s3storage/MinioStorageServiceImpl.java, src/test/java/org/folio/rest/DownloadUrlAPITest.java, src/test/java/org/folio/rest/UploadUrlAPITest.java, src/test/java/org/folio/service/s3storage/MinioStorageServiceTest.java
- Prefix S3 file operations with `data-import/` to improve usability within multi-module buckets
- Added checks for this prefix in S3 calls to prevent potential abuse
- Cleaned up MinIO code to remove redundant future returns (can return `executeBlocking` directly as its `Future` form)
- I also cleaned up the `completeMultipartFileUpload` method to fail on error, rather than succeed with `false`.
- A majority of the changed lines are due to this as well as cleanup in the associated tests
=> [MODDATAIMP-914] Prefix S3 files with data-import/

descriptors/ModuleDescriptor-template.json, ramls/dataImport.raml, src/main/java/org/folio/rest/impl/DataImportImpl.java, src/main/java/org/folio/service/file/SplitFileProcessingService.java, src/test/java/org/folio/rest/CancelJobExecutionTest.java, src/test/java/org/folio/rest/DataImportCancelJobExecutionTest.java
Alter the response of the cancel endpoint to be consistent with the previous SRM-based implementation.
This PR also includes a few fixes for the cancellation logic that seems to have been missing/not merged into the main `release` branch (likely due to hotfixes/testing commits on the `test` branch), as well as a fix to ensure we don't accidentally mark completed jobs as cancelled.
=> [MODDATAIMP-910] Update cancellation endpoint

src/main/java/org/folio/service/auth/SystemUserAuthService.java, src/main/java/org/folio/service/auth/UsersClient.java
https://issues.folio.org/browse/MODCON-92
User type is required now in ECS mode, so each system user should have type='system' populated
=> MODCON-92. Populate system users with type='system' in different modules

descriptors/ModuleDescriptor-template.json, src/main/resources/permissions.txt
The permission `inventory-storage.items.item.get` is needed to process update jobs, however, it was missing from the endpoint (and the system user, too)
=> Add missing permission 

src/main/java/org/folio/rest/impl/DataImportImpl.java, src/main/java/org/folio/service/s3storage/MinioStorageServiceImpl.java, src/test/java/org/folio/rest/AbstractRestTest.java, src/test/java/org/folio/rest/DownloadUrlAPITest.java, src/test/java/org/folio/service/s3storage/MinioStorageServiceTest.java
Getting a presigned URL does not implicitly check that a file exists on S3, which made it possible for download links to be returned for files that no longer exists.  This changes this to only return links when the file is available in S3.
Adds a check by calling [ListObjectsV2](https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjectsV2.html) in S3 before returning a download URL. If the object does not exist, no URL is returned.
=> [MODDATAIMP-908] 404 not found if a S3 download is requested for a file that no longer exists

NEWS.md, src/main/java/org/folio/service/processing/ParallelFileChunkingProcessor.java, src/main/java/org/folio/service/processing/kafka/SourceReaderReadStreamWrapper.java, src/main/java/org/folio/service/util/EventHandlingUtil.java
Upgrade folio-kafka-wrapper to 3.0.0 version
Upgrade the version of folio-kafka-wrapper to 3.0.0-SNAPSHOT. Check out the readme at https://github.com/folio-org/folio-kafka-wrapper/blob/master/README.md for usage.
Acceptance Criteria
- kafka records are built using KafkaProducerRecordBuilder
- topic names are generated using KafkaTopicNameHelper
=> MODDATAIMP-871 Upgrade folio-kafka-wrapper to 3.0.0 version

src/main/java/org/folio/service/file/SplitFileProcessingService.java, src/main/java/org/folio/service/processing/ParallelFileChunkingProcessor.java, src/main/java/org/folio/service/processing/split/FileSplitService.java, src/main/java/org/folio/service/processing/split/FileSplitUtilities.java, src/test/java/org/folio/service/file/SplitFileProcessingServiceAbstractTest.java, src/test/java/org/folio/service/file/SplitFileProcessingServiceStartJobTest.java, src/test/java/org/folio/service/split/FileSplitUtilitiesCountTest.java, src/test/java/org/folio/service/split/FileSplitUtilitiesIsBinaryMarcTest.java, src/test/java/org/folio/service/split/FileSplitWriterRegularTest.java
Currently, all files were fed through the file-splitting process.  However, this system only supports plain binary MARC files (.mrc); as such, MARC JSON, MARC XML, and EDIFACT records were being misprocessed.
Futhermore, the logic used to calculate the number of records in the file was also assuming its type as binary MARC (.mrc).  This changes this logic to use already implemented logic from the file processing components.
This adds utility methods and checks to ensure only binary MARC files (.mrc) are split; all other file types are fed through an alternative workflow.  Additionally, the previously-used MARC record counting was adapted to work with any supported type.
=> [MODDATAIMP-921] Handle non-MARC files properly

README.md, descriptors/ModuleDescriptor-template.json, src/main/java/org/folio/rest/impl/ModTenantAPI.java, src/main/java/org/folio/service/auth/ApiClient.java, src/main/java/org/folio/service/auth/AuthClient.java, src/main/java/org/folio/service/auth/PermissionsClient.java, src/main/java/org/folio/service/auth/SystemUserAuthService.java, src/main/java/org/folio/service/auth/UsersClient.java, src/test/java/org/folio/rest/AbstractRestTest.java, src/test/java/org/folio/service/auth/ApiClientTest.java, src/test/java/org/folio/service/auth/AuthClientTest.java, src/test/java/org/folio/service/auth/SystemUserAuthServiceTest.java, src/test/java/org/folio/service/auth/UsersClientTest.java, src/test/java/org/folio/service/file/S3JobRunningVerticleEnabledIntegrationTest.java
Remove the default system user password.  This PR also cleans up a bit of the infrastructure around these API requests, to make them cleaner and more readable/maintainable.
Adds logic to ensure splitting is enabled before creating the system user.  Also, the password environment variable is checked to ensure it's set when needed (and will fail tenant install if not).
Additional logic was added to handle cases where the password may change with time, to allow hosting providers to implement rolling passwords/etc.
=> [MODDATAIMP-940] [Poppy] Remove system user default password

src/main/java/org/folio/service/file/SplitFileProcessingService.java
The module would occasionally become unresponsive when under large load, causing concurrent file splits or uploads to be difficult or unresponsive.
This change adds a dedicated worker to execute file splits, allowing better sharing of the event loop.
=> [MODDATAIMP-939] [Poppy] Use dedicated non-blocking worker for splitting files

src/main/java/org/folio/service/file/SplitFileProcessingService.java
The module would occasionally become unresponsive when under large load, causing concurrent file splits or uploads to be difficult or unresponsive.
This change adds a dedicated worker to execute file splits, allowing better sharing of the event loop.
=> [MODDATAIMP-939] [Orchid] Use dedicated non-blocking worker for splitting files

src/main/java/org/folio/rest/impl/ModTenantAPI.java, src/main/java/org/folio/service/auth/AuthClient.java, src/main/java/org/folio/service/auth/SystemUserAuthService.java, src/test/java/org/folio/rest/AbstractRestTest.java, src/test/java/org/folio/service/auth/SystemUserAuthServiceTest.java
With Poppy, certain changes were made to user logins/token management.  We updated the code here to handle this, however, missed a couple spots relating to password setting on tenant install.
Ensure proper handling of login results when installing on tenant
=> [MODDATAIMP-947] Fix improper system user account management

NEWS.md, pom.xml
Update folio-s3-client to v2.0.5
JIRA: https://issues.folio.org/browse/MODDATAIMP-969.
=> MODDATAIMP-969: Update folio-s3-client to v2.0.5

descriptors/ModuleDescriptor-template.json
Add permissions for creating/updating MARC Bib by DI
Add following permissions:
- source-storage.records.post
- source-storage.records.put
In mod-data-import for
**/data-import/uploadDefinitions/{uploadDefinitionId}/processFiles**
=> [MODDATAIMP-983] Add permissions for creating/updating MARC Bib by DI

NEWS.md, src/main/java/org/folio/rest/impl/DataImportImpl.java, src/main/java/org/folio/service/file/SplitFileProcessingService.java, src/main/java/org/folio/service/storage/LocalFileStorageService.java, src/test/java/org/folio/rest/ProcessS3APITest.java
The main goal is to make /data-import/uploadDefinitions/{id}/processFiles?defaultMapping=false as async to fix FAT tests.
Also added updating Job status if  it is failed.
Complete future, not waiting processing files.
Additional safe check added to another logic.
https://folio-org.atlassian.net/browse/MODDATAIMP-1007
=> MODDATAIMP-1007: Make endpoint as async.

descriptors/ModuleDescriptor-template.json
[MODDATAIMP-1050](https://folio-org.atlassian.net/browse/MODDATAIMP-1050) Missing interface dependencies in module descriptor
add configuration interface as required interface
=> MODDATAIMP-1050 Missing interface dependencies in module descriptor

scripts/load-marc-data-into-folio-with-split-files-enabled.sh
The bash script for importing files via API does not work.
Getting the ETag HTTP header is made case-insensitive.
[MODDATAIMP-1055](https://folio-org.atlassian.net/browse/MODDATAIMP-1055)
=> MODDATAIMP-1055: Fix receiving ETag HTTP header value

descriptors/ModuleDescriptor-template.json
The main purpose is to update default mapping for Date type, Date 1, and Date 2 fields
So there should be extended our default mapper. Previouslym we did NOT map simple JsonObjects, just String or Arrays. In our case, the "Dates" - is an object, and our mapper can't work with this type of Instance's field. So there was added a new property to rules named "createSingleObject". And if mapper find this rules - it will handle this rule via specific logic, building rules into 1 JsonObject. 
1. New Pemission added.
JIRA: https://folio-org.atlassian.net/browse/MODSOURMAN-1228
**NOTE**: This PR should be merged **ONLY** with these 2: https://github.com/folio-org/data-import-processing-core/pull/367 AND https://github.com/folio-org/data-import-processing-core/pull/367
=> MODSOURMAN-1228: Permission added.

descriptors/ModuleDescriptor-template.json
[MODDATAIMP-1100](https://folio-org.atlassian.net/browse/MODDATAIMP-1100)
Data-import karate tests falls into infinity loop, breaking CI Quality Gates pipeline
Add missing permissions
Old permission | New permissions
-- | --
data-import.uploaddefinitions.get | data-import.uploadDefinitions.item.get, data-import.uploadDefinitions.collection.get
data-import.uploaddefinitions.files.post | data-import.uploadDefinitions.files.item.post, data-import.uploadDefinitions.processFiles.item.post
data-import.fileExtensions.get | data-import.fileExtensions.item.get, data-import.fileExtensions.collection.get
data-import.fileExtensions.default | data-import.fileExtensions.default.post
data-import.uploadUrl.get | data-import.uploadUrl.item.get, data-import.uploadUrl.subsequent.item.get …
=> MODDATAIMP-1100 Add missing permissions

.github/workflows/postgres.yml, NEWS.md, pom.xml
[MODDATAIMP-1099](https://folio-org.atlassian.net/browse/MODDATAIMP-1099) mod-data-import Ramsons 2024 R2 - RMB v35.3.x update
Upgrade to RMB v35.3
Follow the [RMB upgrade notes for 35.3.x](https://github.com/folio-org/raml-module-builder/releases/tag/v35.3.0) upgrade.
Upgrade Vertx to 4.5.7 version.
=> MODDATAIMP-1099 mod-data-import Ramsons 2024 R2 - RMB v35.3.x update

NEWS.md, pom.xml, src/main/java/org/folio/service/file/S3JobRunningVerticle.java, src/main/java/org/folio/service/processing/ParallelFileChunkingProcessor.java
Remove X-OKAPI-TOKEN header from Kafka messages 
[MODDATAIMP-1121](https://folio-org.atlassian.net/browse/MODDATAIMP-1121)
=> MODDATAIMP-1121 Remove X-OKAPI-TOKEN header from Kafka messages

pom.xml, src/test/java/org/folio/rest/UploadDefinitionAPITest.java
https://folio-org.atlassian.net/browse/MODDATAIMP-1190
Fix this security vulnerability in Netty:
* CVE-2025-24970 https://github.com/netty/netty/security/advisories/GHSA-4g8c-wm8x-jfhw – netty-handler SslHandler/SSLEngine native crash
Upgrade Vertx from 4.5.7 to 4.5.14.
Upgrade AWS S3 client from 2.29.6 to 2.31.21.
These two upgrades indirectly upgrade Netty from 4.1.108.Final to 4.1.118.Final fixing the security vulnerability:
Update UploadDefinitionAPITest to
* fix any race condition
* remove useless Async
* fix postFilesProcessingWithUnprocessableEntity() and remove its `@Ignore`
=> MODDATAIMP-1190: Netty 4.1.118 (Vert.x 4.5.14, AWS S3 2.31.21) fix vuln

descriptors/ModuleDescriptor-template.json
[MODORDERS-1269](https://folio-org.atlassian.net/browse/MODORDERS-1269) - Remove alerts and reporting codes from order lines, use a single order line schema
Use a single po line schema, no more "composite po line", remove unused permissions
See https://github.com/folio-org/mod-orders-storage/pull/477
Required for compilation: https://github.com/folio-org/acq-models/pull/520
=> MODORDERS-1269. Remove unnecessary permissions after deleting alerts and reporting codes

NEWS.md, descriptors/ModuleDescriptor-template.json
to restrict shared instance/record update through data import
* add permission that will allow update of shared instance/record through data import
[MODDATAIMP-1214](https://issues.folio.org/browse/MODDATAIMP-1214)
=> MODDATAIMP-1214 - Add permission to permit update of shared instance and MARC

NEWS.md, src/main/java/org/folio/dao/DataImportQueueItemDao.java, src/main/java/org/folio/dao/DataImportQueueItemDaoImpl.java, src/main/java/org/folio/service/processing/ParallelFileChunkingProcessor.java, src/test/java/org/folio/dao/DataImportQueueDaoTest.java
to fix "file contains duplicates" error that occurs when importing large files
* fix lock acquisition and transactional operations to ensure that imported file is processed by one worker
* update tests
[MODDATAIMP-1223](https://issues.folio.org/browse/MODDATAIMP-1223)
=> MODDATAIMP-1223 - File splitting (DI) creating duplicate records
