folio-org/mod-data-import

NEWS.md, pom.xml, ramls/dataImport.raml, src/main/java/org/folio/dao/FileDao.java, src/main/java/org/folio/dao/FileDaoImpl.java, src/main/java/org/folio/dao/UploadDefinitionDao.java, src/main/java/org/folio/dao/UploadDefinitionDaoImpl.java, src/main/java/org/folio/rest/impl/DataImportImpl.java, src/main/java/org/folio/service/FileService.java, src/main/java/org/folio/service/FileServiceImpl.java, src/main/java/org/folio/service/FileStorageService.java, src/main/java/org/folio/service/UploadDefinitionService.java, src/main/java/org/folio/service/UploadDefinitionServiceImpl.java, src/main/java/org/folio/util/DataImportHelper.java, src/test/java/org/folio/rest/RestVerticleTest.java
* Design service methods
* Add all methods to interface and javadocs
* Use methods calls at API endpoints
=> Moddataimp 33

descriptors/ModuleDescriptor-template.json, src/main/java/org/folio/dao/UploadDefinitionDao.java, src/main/java/org/folio/dao/UploadDefinitionDaoImpl.java, src/main/java/org/folio/rest/impl/DataImportImpl.java, src/main/java/org/folio/service/file/FileService.java, src/main/java/org/folio/service/file/FileServiceImpl.java, src/main/java/org/folio/service/storage/AbstractFileStorageService.java, src/main/java/org/folio/service/storage/FileStorageService.java, src/main/java/org/folio/service/storage/FileStorageServiceBuilder.java, src/main/java/org/folio/service/storage/LocalFileStorageService.java, src/main/java/org/folio/service/upload/UploadDefinitionService.java, src/main/java/org/folio/service/upload/UploadDefinitionServiceImpl.java, src/main/java/org/folio/util/ConfigurationUtil.java, src/main/java/org/folio/util/OkapiConnectionParams.java, src/main/java/org/folio/util/RestUtil.java, src/test/java/org/folio/rest/RestVerticleTest.java
Changes:
add ret call to mod-source-record-manager
replace jobExecution ids from a response
add mocks for API tests
-bugfixing
add blocking update mechanism
=> Moddataimp 41

ramls/dataImport.raml, src/main/java/org/folio/rest/impl/DataImportImpl.java, src/main/java/org/folio/service/processing/FileProcessor.java, src/main/java/org/folio/service/processing/ParallelFileChunkingProcessor.java
fixed code smells,
apply fileProcessingRqDto
fix java doc to proper version
=> Moddataimp 45 - fixing code smells

src/main/java/org/folio/service/upload/UploadDefinitionServiceImpl.java, src/test/java/org/folio/rest/RestVerticleTest.java
=> change validation message

src/main/java/org/folio/service/processing/ParallelFileChunkingProcessor.java, src/main/java/org/folio/service/processing/reader/SourceReaderBuilder.java, src/test/java/org/folio/service/processing/ParallelFileChunkingProcessorUnitTest.java
* Fixing code smells in the scope of MODDATAIMP-45
=> MODDATAIMP-45 -fixed code smells

FileProcessingApi.md, NEWS.md, pom.xml, ramls/dataImport.raml
* Updated NEWS.md
* Added API documentation for file processing
* API version was changed from 1.1 to 2.0 before this pull request !!!
=> MODDATAIMP-78 - Update mod-data-import API documentation

pom.xml, src/main/java/org/folio/rest/impl/DataImportImpl.java, src/main/java/org/folio/service/processing/FileProcessor.java, src/test/java/org/folio/rest/AbstractRestTest.java, src/test/java/org/folio/rest/UploadDefinitionAPITest.java
Estimated code coverage after merge 79.1%, code coverage 80% will be reached after fixing bug:
https://issues.folio.org/browse/MODDATAIMP-95
=> Moddataimp 87

ramls/dataImport.raml, src/main/java/org/folio/rest/impl/DataImportImpl.java, src/main/java/org/folio/service/processing/ParallelFileChunkingProcessor.java, src/main/java/org/folio/service/processing/reader/SourceReaderBuilder.java, src/test/java/org/folio/rest/AbstractRestTest.java, src/test/java/org/folio/rest/FileExtensionAPITest.java, src/test/java/org/folio/rest/UploadDefinitionAPITest.java, src/test/java/org/folio/service/processing/ParallelFileChunkingProcessorUnitTest.java
Implement the way RecordFormat is defined by JobExecution
=> Modsourman 80

src/main/java/org/folio/rest/impl/InitFileProcessorAPI.java, src/test/java/org/folio/rest/AbstractRestTest.java, src/test/java/org/folio/rest/UploadDefinitionAPITest.java
* Moved InitFileProcessorAPI to rest.impl package
* Refactored tests
=> MODDATAIMP-101

descriptors/ModuleDescriptor-template.json
Add dependencies on users interface
=> MODDATAIMP-120

NEWS.md, src/main/java/org/folio/service/processing/ParallelFileChunkingProcessor.java, src/main/java/org/folio/service/processing/reader/MarcJsonReader.java, src/main/java/org/folio/service/processing/reader/MarcRawReader.java, src/main/java/org/folio/service/processing/reader/MarcXmlReader.java, src/main/java/org/folio/service/processing/reader/SourceReader.java, src/test/java/org/folio/service/processing/ParallelFileChunkingProcessorUnitTest.java, src/test/resources/invalidUChicago_SampleBibs.xml
-added contentType field to the RawRecordsDto
=> MODSOURMAN-112 Implement a more elaborate way to define a RecordParser

NEWS.md, pom.xml
=> Tmp release 1.5.0

NEWS.md, pom.xml, ramls/dataImport.raml, src/main/java/org/folio/rest/impl/DataImportImpl.java, src/main/java/org/folio/service/processing/FileProcessor.java, src/main/java/org/folio/service/processing/ParallelFileChunkingProcessor.java, src/test/java/org/folio/rest/UploadDefinitionAPITest.java, src/test/java/org/folio/service/processing/ParallelFileChunkingProcessorUnitTest.java
In scope of story MODSOURMAN-260 I added defaultMapping query param.
=> MODSOURMAN-260 Added defaultMapping query param

src/main/java/org/folio/service/processing/ParallelFileChunkingProcessor.java, src/main/resources/log4j2.properties
=> Synchronization fix

descriptors/ModuleDescriptor-template.json, src/main/java/org/folio/config/ApplicationConfig.java, src/test/java/org/folio/rest/AbstractRestTest.java, src/test/java/org/folio/service/config/ApplicationTestConfig.java
Set correct env variables names for kafka config
=> Fix kafka config

descriptors/ModuleDescriptor-template.json
to create invoice and invoice lines mapped from incoming edifact record
=> MODINVOICE-231 - Added permissions for invoice creation

.rancher-pipeline.yml, src/main/java/org/folio/service/processing/ParallelFileChunkingProcessor.java, src/main/java/org/folio/service/processing/kafka/SourceReaderReadStreamWrapper.java
To provide more common naming for events
* changed event from `DI_RAW_MARC_BIB_RECORDS_CHUNK_READ` to more common - `DI_RAW_RECORDS_CHUNK_READ`
[MODSOURMAN-412](https://issues.folio.org/browse/MODSOURMAN-412)
=> MODSOURMAN-412 Restructure MARC related events to have common and type specific ones 

README.md
=> MODDATIMP-431: Update module readme files to reflect Iris environment  variables.

NEWS.md, descriptors/ModuleDescriptor-template.json
Due to changes made in scope of https://issues.folio.org/browse/MODDATAIMP-451 interfaces version should be updated to notify dependant modules about changes. 
* updated interface version for "source-manager-job-executions", "source-manager-records" from 1.0 to 3.0
=> MODDATAIMP-451 - Update interface version

descriptors/ModuleDescriptor-template.json
fix interface version
* updated interface version for "source-manager-job-executions", "source-manager-records" to 2.0
=> MODDATAIMP-454 - Update interface version

pom.xml
=> MODDPUBSUB-181: Update folio-kafka-wrapper version to 2.4.0-SNAPSHOT

pom.xml
=> MODPUBSUB-181: Bump folio-kafka-wrapper version to 2.3.1

descriptors/ModuleDescriptor-template.json
Add missed `inventory-storage.holdings-sources.collection.get` permission
=> MODDATAIMP-666 Add missed `inventory-storage.holdings-sources.collection.get` permission

descriptors/ModuleDescriptor-template.json
https://issues.folio.org/browse/MODDATAIMP-714
=> MODDATAIMP-714 Add authority source files permission

NEWS.md, pom.xml, src/test/java/org/folio/rest/AbstractRestTest.java, src/test/java/org/folio/rest/ModTenantApiTest.java
Upgrade to RMB v35.0.0
[MODDATAIMP-721](https://issues.folio.org/browse/MODDATAIMP-721)
=> MODDATAIMP-721: Upgrade to RMB v35.0.0

pom.xml
Exception: KafkaException: Producer closed while send in progress
Revert to vertx 4.3.1
[MODSOURMAN-893](https://issues.folio.org/browse/MODSOURMAN-893)
=> MODSOURMAN-893: Revert to vertx 4.3.1

NEWS.md, pom.xml, src/main/java/org/folio/service/processing/ParallelFileChunkingProcessor.java, src/main/java/org/folio/service/util/EventHandlingUtil.java
KafkaException: Producer closed while send in progress 
after upgrade to vertx 4.3.4
Fixed manual control of producer closures
[MODDATAIMP-727](https://issues.folio.org/browse/MODDATAIMP-727)
=> MODDATAIMP-727: Upgrade to vertx 4.3.4

PULL_REQUEST_TEMPLATE.md, src/main/resources/log4j2.properties
Logging improvement - Configuration
Jira: https://issues.folio.org/browse/MODDATAIMP-724
=> [MODDATAIMP-724] Logging improvement - Configuration

src/main/resources/log4j2-json.properties, src/main/resources/log4j2.properties
Adjust logging configuration for MOD-DI to display datetime in a proper format
Changed logs configuration
=> [MODDATAIMP-736] Adjust logging configuration for MOD-DI to display datetime in a proper format

src/main/java/org/folio/config/ApplicationConfig.java, src/main/java/org/folio/dao/FileExtensionDaoImpl.java, src/main/java/org/folio/dao/UploadDefinitionDaoImpl.java, src/main/java/org/folio/rest/impl/DataImportImpl.java, src/main/java/org/folio/service/cleanup/StorageCleanupServiceImpl.java, src/main/java/org/folio/service/file/FileUploadLifecycleServiceImpl.java, src/main/java/org/folio/service/fileextension/FileExtensionServiceImpl.java, src/main/java/org/folio/service/processing/ParallelFileChunkingProcessor.java, src/main/java/org/folio/service/processing/kafka/SourceReaderReadStreamWrapper.java, src/main/java/org/folio/service/processing/kafka/WriteStreamWrapper.java, src/main/java/org/folio/service/processing/reader/EdifactReader.java, src/main/java/org/folio/service/processing/reader/MarcJsonReader.java, src/main/java/org/folio/service/processing/reader/MarcRawReader.java, src/main/java/org/folio/service/processing/reader/MarcXmlReader.java, src/main/java/org/folio/service/storage/LocalFileStorageService.java, src/main/java/org/folio/service/upload/UploadDefinitionServiceImpl.java, src/main/java/org/folio/service/util/EventHandlingUtil.java, src/test/java/org/folio/service/config/ApplicationTestConfig.java
Logging improvement
Added new and changed old logs
=> [MODDATAIMP-641] Logging improvement

descriptors/ModuleDescriptor-template.json
to provide permissions for order creation
[MODORDERS-773](https://issues.folio.org/browse/MODORDERS-773)
=> MODORDERS-773 - Provided permissions for order creation

src/main/resources/log4j2-json.properties, src/main/resources/log4j2.properties
https://issues.folio.org/browse/MODDATAIMP-758
=> [MODDATAIMP-758]Imrove logging (hide SQL requests)

descriptors/ModuleDescriptor-template.json
Update endpoints:
POST /data-import/uploadDefinitions/{uploadDefinitionId}/processFiles
with module permissions:
instance-authority-links.instances.collection.get
instance-authority-links.instances.collection.put
=> MODDATAIMP-768 Update permissions for links update

pom.xml
Update dependencies
Bumped dependencies versions
=> [MODDATAIMP-750] Update dependencies

pom.xml
Update data-import-processing-core dependency
Updated dependency
=> [MODDICORE-306] Update data-import-processing-core dependency

descriptors/ModuleDescriptor-template.json
Update permissions
- Add linking-rules permission
[MODSOURMAN-974](https://issues.folio.org/browse/MODSOURMAN-974)
=> MODSOURMAN-974 MARC bib $9 handling | Remove $9 subfields from linkable fields

.github/workflows/api-doc.yml, .github/workflows/api-lint.yml, .github/workflows/api-schema-lint.yml, Jenkinsfile, README.md, ramls/dataImport.raml
[FOLIO-3678](https://issues.folio.org/browse/FOLIO-3678)
Use GitHub Workflows for [api-lint](https://dev.folio.org/guides/api-lint/) and [api-schema-lint](https://dev.folio.org/guides/describe-schema/) and [api-doc](https://dev.folio.org/guides/api-doc/)
(instead of Jenkins-operated CI stages).
=> FOLIO-3678 MODDATAIMP-815 Use GitHub Workflows api-lint and api-schema-lint and api-doc

pom.xml
Update changes from https://github.com/folio-org/mod-data-import/pull/251 into Orchid release branch
=> Update version of test containers to support Mac M1 processor (Orchid release branch)

descriptors/ModuleDescriptor-template.json, ramls/dataImport.raml, src/main/java/org/folio/rest/impl/DataImportImpl.java, src/test/java/org/folio/rest/DataImportSplitTest.java
To provide an api endpoint that returns configuration status for splitting of data import files to the UI for use in its internal flow and messaging.  Defaults to false if no value is present in the classpath.
Creates a spring @value variable which will pull the status variable from environment variables or properties.  
I considered adding an affirmative test where it set the environment variable and then returned it, however this is simply testing spring functionality for injecting that value.
=> Moddataimp 852 configure api for workflow

pom.xml
_Upgrade `aspectj-maven-plugin` to Java 17 wIthin the scope of the whole module migration._
_`groupId` of `aspectj-maven-plugin` is migrated from `com.nickwongdev` to `dev.aspectj`._
=> MODDATAIMP-854: Upgrade aspectj-maven-plugin to Java 17

descriptors/ModuleDescriptor-template.json
Module descriptor changes were forgotten on previous 874 PR
Modify MD for new api call
None
None
=> 874 fix module descriptor

src/main/java/org/folio/service/file/S3JobRunningVerticle.java, src/main/java/org/folio/service/file/SplitFileProcessingService.java, src/test/java/org/folio/rest/CancelJobExecutionTest.java, src/test/java/org/folio/service/file/SplitFileProcessingServiceStartJobTest.java
Test branch version of #288 
MODDATAIMP-911 add the totalRecordsInFile field to the Entity and DTO to support correct progress bar in UI-data-import application.
=> [MODDATAIMP-911] [Test branch] Add totalRecordsInFile field for JobExecutions

README.md, descriptors/ModuleDescriptor-template.json, src/main/java/org/folio/rest/impl/ModTenantAPI.java, src/main/java/org/folio/service/auth/ApiClient.java, src/main/java/org/folio/service/auth/AuthClient.java, src/main/java/org/folio/service/auth/PermissionsClient.java, src/main/java/org/folio/service/auth/SystemUserAuthService.java, src/main/java/org/folio/service/auth/UsersClient.java, src/test/java/org/folio/rest/AbstractRestTest.java, src/test/java/org/folio/service/auth/ApiClientTest.java, src/test/java/org/folio/service/auth/AuthClientTest.java, src/test/java/org/folio/service/auth/SystemUserAuthServiceTest.java, src/test/java/org/folio/service/auth/UsersClientTest.java, src/test/java/org/folio/service/file/S3JobRunningVerticleEnabledIntegrationTest.java
Remove the default system user password.  This PR also cleans up a bit of the infrastructure around these API requests, to make them cleaner and more readable/maintainable.
Adds logic to ensure splitting is enabled before creating the system user.  Also, the password environment variable is checked to ensure it's set when needed (and will fail tenant install if not).
Additional logic was added to handle cases where the password may change with time, to allow hosting providers to implement rolling passwords/etc.
=> [MODDATAIMP-940] [Orchid] Remove system user default password

pom.xml
folio-s3-client updated to v2.0.0.
JIRA: https://issues.folio.org/browse/MODDATAIMP-966
=> MODDATAIMP-966: Update folio-s3-client to v2.0.0

pom.xml
Update folio-s3-client to v2.0.4.
JIRA: https://issues.folio.org/browse/MODDATAIMP-966
=> MODDATAIMP-966: Update folio-s3-client to v2.0.4

src/main/java/org/folio/service/kafka/DIKafkaTopicService.java, src/main/java/org/folio/service/kafka/support/DataImportKafkaTopic.java, src/test/java/org/folio/service/kafka/KafkaAdminClientServiceTest.java
=> Add def namespace for topics

NEWS.md, descriptors/ModuleDescriptor-template.json
Provide "orders-storage.titles.item.get" module permission [MODDATAIMP-1003](https://folio-org.atlassian.net/browse/MODDATAIMP-1003)
* add permission into module permissions
=> MODDATAIMP-1003 Provide "orders-storage.titles.item.get" module permission

descriptors/ModuleDescriptor-template.json
Add permission for snapshot post
Added permission for snapshot post
=> [MODINV-972] Add permission for snapshot post

NEWS.md, pom.xml, src/main/java/org/folio/service/processing/FileProcessor.java, src/main/java/org/folio/service/processing/ranking/ScoreUtils.java, src/main/java/org/folio/service/processing/split/FileSplitWriterOptions.java, src/main/java/org/folio/service/s3storage/MinioStorageService.java
Upgrade data-import to RMB v35.2.0 and Vertx 4.5.4
[MODDATAIMP-1015](https://folio-org.atlassian.net/browse/MODDATAIMP-1015)
=> MODDATAIMP-1015: Upgrade data-import to RMB v35.2.0 and Vertx 4.5.4

NEWS.md, scripts/load-marc-data-into-folio-with-split-files-enabled.sh
[MODDATAIMP-1054](https://folio-org.atlassian.net/browse/MODDATAIMP-1054) Add error handling for script interrupts
* added validations
=> MODDATAIMP-1054 Add error handling for script interrupts

NEWS.md, src/main/java/org/folio/service/file/SplitFileProcessingService.java
The main goal is to avoid stucking data-import feature after running integration tests.
It seems like there are jobs with stucked "LOADED" status. There is a chance that the current code will update upload definition b status.
JIRA: https://folio-org.atlassian.net/browse/MODDATAIMP-1046
=> MODDATAIMP-1046: Spike: "File upload already in progress" appears when data import job was run for more than one file.

NEWS.md, src/main/java/org/folio/service/file/SplitFileProcessingService.java, src/main/java/org/folio/service/upload/UploadDefinitionServiceImpl.java
=> MODDATAIMP-1046: Spike

scripts/load-marc-data-into-folio.sh
Remove references on deprecated default job profile 'Create MARC Bibs' 
Removed references on deprecated default job profile 'Create MARC Bibs' 
https://folio-org.atlassian.net/browse/MODDICONV-389
=> [MODDICONV-389] Remove references on deprecated default job profile 'Create MARC Bibs' 

NEWS.md, src/main/java/org/folio/service/processing/split/FileSplitWriter.java, src/main/java/org/folio/service/s3storage/MinioStorageServiceImpl.java, src/test/java/org/folio/service/processing/split/FileSplitWriterS3ExceptionalTest.java
[MODDATAIMP-1082](https://folio-org.atlassian.net/browse/MODDATAIMP-1082) Improve error logging for AWS-related issue.
add additional logs when s3 exception, pass exceptions properly
=> MODDATAIMP-1082 Improve error logging for AWS-related issue.

descriptors/ModuleDescriptor-template.json
Add module permissions for extend mapping params with other ref data necessary for Orders mappings
=> [MODORDERS-1181] Add module permissions for extend mapping params with other ref data necessary for Orders mappings

descriptors/ModuleDescriptor-template.json
=> MODFIN-377 clean up mod-finance permissions

descriptors/ModuleDescriptor-template.json
=> MODDATAIMP-1100

pom.xml
Update folio-s3-client dependency to 2.2.1
=> Update folio-s3-client dependency to 2.2.1

src/main/java/org/folio/service/file/FileUploadLifecycleServiceImpl.java
Bulk edit MARC flow fails to commit by User
Handle afterFileSave futures successively
=> [MODDATAIMP-1124] Handle afterFileSave futures successively

src/main/java/org/folio/dao/UploadDefinitionDaoImpl.java
Fix bulk edit stuck
Get upload definition by id directly from W DB instance
=> [MODDATAIMP-1124] Get upload definition by id directly from W DB instance

.github/workflows/postgres.yml, .rancher-pipeline.yml, Dockerfile, Jenkinsfile, NEWS.md, pom.xml, src/test/java/org/folio/rest/AbstractRestTest.java, src/test/java/org/folio/rest/ProcessS3APITest.java
Update to Java 21
- Updated to Java 21
- Fixed inline-mocks by adding a byte-buddy dependency
https://folio-org.atlassian.net/browse/MODDATAIMP-1176
=> [MODDATAIMP-1176] Update to Java 21

pom.xml, src/main/java/org/folio/service/processing/kafka/SourceReaderReadStreamWrapper.java, src/main/java/org/folio/service/processing/reader/model/EdifactFooterState.java, src/main/java/org/folio/service/processing/reader/model/EdifactInvoiceFinishState.java
In the new version 1.25.3 of io.xlate.staedi library, file structure checking has become more stringent. 
Fixed algorithm of EDIFACT records preparation
[MODDATAIMP-1206](https://folio-org.atlassian.net/browse/MODDATAIMP-1206)
=> MODDATAIMP-1206: The invoice is not created after importing .edi file
